actions:
- '.github/**/*'

test:
- src/**/*.spec.js
- src/**/*.spec.ts
- src/**/*.test.js
- src/**/*.test.ts
- src/**/__tests__/**/*
- __tests__/**/*
- tests/**/*

documetation:
- '.docs/**/*'
- 'docs/**/*'
- 'doc/**/*'
- 'documentation/**/*'

âš™ï¸ configuration:
- '.idea/**/*'
- '.github/**/*'
- '.vscode/**/*'
- '.husky/**/*'
- '.lintstagedrc'
- '.prettierrc'
- '.eslintrc'
- '.editorconfig'
- '.gitignore'
- '.gitattributes'
- '.npmignore'
- '.npmrc'
- '*.config.js'
- '*.config.ts'

ğŸ“¦ dependencies:
- 'package.json'
- 'package-lock.json'